### PR TITLE
[RFE] [WIP] Switch to Python3

### PR DESCRIPTION
**Pull request by lemenkov**
Hello!
This is an initial attempt to switch everything to Python3. It's a work-in-progress (slide-bar for current playing position isn't working yet) so not ready for merging but fairly usable.

Any comments and critics is highly appreciated :)

### CODE REVIEW

**Comment by lemenkov** [comment]
It's a little bit huge indeed. I believe some patches can be merged into current Python2 version. I'll try to cherry-pick them and create another one PR with just them.

**Comment by lemenkov** [comment]
Thanks, @foobnix - that was fast :)

**Comment by foobnix** [comment]
@lemenkov  no one support foobnix now, you are only one contributor, do what you want :))

**Comment by foobnix** [comment]
@lemenkov please make build for ubuntu 18+and 19+ if you can,  users ask about this

**Pull request merged**
